/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedScannerRouteImport } from './routes/_authenticated/scanner'
import { Route as AuthenticatedParticipantesRouteImport } from './routes/_authenticated/participantes'
import { Route as AuthenticatedAdministracaoRouteImport } from './routes/_authenticated/administracao'
import { Route as AuthenticatedParticipanteCodigoRouteImport } from './routes/_authenticated/participante.$codigo'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScannerRoute = AuthenticatedScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParticipantesRoute =
  AuthenticatedParticipantesRouteImport.update({
    id: '/participantes',
    path: '/participantes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministracaoRoute =
  AuthenticatedAdministracaoRouteImport.update({
    id: '/administracao',
    path: '/administracao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParticipanteCodigoRoute =
  AuthenticatedParticipanteCodigoRouteImport.update({
    id: '/participante/$codigo',
    path: '/participante/$codigo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/participantes': typeof AuthenticatedParticipantesRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/participante/$codigo': typeof AuthenticatedParticipanteCodigoRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/participantes': typeof AuthenticatedParticipantesRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/': typeof AuthenticatedIndexRoute
  '/participante/$codigo': typeof AuthenticatedParticipanteCodigoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/administracao': typeof AuthenticatedAdministracaoRoute
  '/_authenticated/participantes': typeof AuthenticatedParticipantesRoute
  '/_authenticated/scanner': typeof AuthenticatedScannerRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/participante/$codigo': typeof AuthenticatedParticipanteCodigoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/administracao'
    | '/participantes'
    | '/scanner'
    | '/participante/$codigo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/administracao'
    | '/participantes'
    | '/scanner'
    | '/'
    | '/participante/$codigo'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/administracao'
    | '/_authenticated/participantes'
    | '/_authenticated/scanner'
    | '/_authenticated/'
    | '/_authenticated/participante/$codigo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scanner': {
      id: '/_authenticated/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AuthenticatedScannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/participantes': {
      id: '/_authenticated/participantes'
      path: '/participantes'
      fullPath: '/participantes'
      preLoaderRoute: typeof AuthenticatedParticipantesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracao': {
      id: '/_authenticated/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AuthenticatedAdministracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/participante/$codigo': {
      id: '/_authenticated/participante/$codigo'
      path: '/participante/$codigo'
      fullPath: '/participante/$codigo'
      preLoaderRoute: typeof AuthenticatedParticipanteCodigoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdministracaoRoute: typeof AuthenticatedAdministracaoRoute
  AuthenticatedParticipantesRoute: typeof AuthenticatedParticipantesRoute
  AuthenticatedScannerRoute: typeof AuthenticatedScannerRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedParticipanteCodigoRoute: typeof AuthenticatedParticipanteCodigoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdministracaoRoute: AuthenticatedAdministracaoRoute,
  AuthenticatedParticipantesRoute: AuthenticatedParticipantesRoute,
  AuthenticatedScannerRoute: AuthenticatedScannerRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedParticipanteCodigoRoute: AuthenticatedParticipanteCodigoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
